[package]
name = "uefi-bootloader"
version = "0.1.0"
edition = "2021"

[dependencies]
bit_field = "*"
cfg-if = "*"
derive_more = "*"
log = "*"
paste = "*"
spin = "*"
uefi = { version = "*", default-features = false }
zerocopy = "*"

[dependencies.goblin]
version = "*"
default-features = false
features = ["elf64"]

[dependencies.noto-sans-mono-bitmap]
version = "*"
default-features = false
features = [
  "regular",
  "size_16",
  "unicode-basic-latin",
  # required for the fallback char 'ï¿½'
  "unicode-specials",
]

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "*"
